# Generated by Django 4.2.17 on 2024-12-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1player1', models.CharField(max_length=100)),
                ('team1player2', models.CharField(max_length=100)),
                ('team1_game_score', models.IntegerField()),
                ('team2player1', models.CharField(max_length=100)),
                ('team2player2', models.CharField(max_length=100)),
                ('team2_game_score', models.IntegerField()),
            ],
        ),
    ]
