# Generated by Django 4.2.17 on 2024-12-26 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'matches'},
        ),
        migrations.AlterField(
            model_name='match',
            name='team1player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team1player1', to='players.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team1player2', to='players.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team2player1', to='players.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team2player2', to='players.player'),
        ),
    ]
