# Generated by Django 4.2.17 on 2025-06-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_options_alter_match_team1player1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team1_game_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2_game_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
